### ISSUE TITLE
Add an updated stack view in the bottom tabbed window

### ISSUE THREAD

**Issue by kirinyaga** [kierenj/0x10c-DevKit#100]
So we can easily see where we come from when a breakpoint is reached, and look at current function pushed parameters.

**Comment by kierenj** [comment]
Did you have a plain word dump starting at SP in mind?  It would be possible to modify/hook the emulation core and highlight words added as the result of PC being pushed to the stack vs a label (i.e. differentiation the method call locations vs parameters).

**Comment by kirinyaga** [comment]
Yep, a list of memory locations with the [SP] always at top. And a third column listing the label matching the value and/or the filename+line#. If you can mark the values originating from PC to display line# only for them it's even better. If you can add the last non-relative label seen before this address (=probably the function name or buffer name), it's perfect.

**Comment by kierenj** [comment]
Stack view now added, complete with debug info to show symbols/offsets
