### ISSUE TITLE
Memory Monitor

### ISSUE THREAD

**Issue by rustyoz** [kierenj/0x10c-DevKit#103]
A monitor for memory would be good. 

All memory locations could be listed with an index, the value of word in hex, bin and dec, maybe even ascii character as well.  

Also Dcpu studio has its handy follow feature where it will highlight where the memory last wrote to in a memory monitor and if any register has changed

**Comment by kierenj** [comment]
There is already a memory view in DevKit.  Currently each location is displayed in hex and an ASCII character where possible (as is the standard for memory views).  I am not convinced binary or decimal views are of much use (can you give me a good example of use?).  Highlighting recently-changed memory locations is a good idea for a feature, I will raise a separate Issue.

**Comment by rustyoz** [comment]
Ah i found it. Yeah its much better than DCPU studio's too. 

I was going to suggest decimal values could be good for comparing text strings in memory, but since you have the character output, the only thing i can think of at the moment is sensor readings. 

Also with the highlighting, you could run the cpu in 2 different modes along the lines of full trace mode and difference mode. In full trace mode, changes are updates each cycle in the monitors. In difference they would be updated at each break like they currently are. 

Also if you could zoom the memory monitor combined with persistent highlighting of changed memory values, it would allow for a good visual representation where activity is taking place

**Comment by kierenj** [comment]
Updating each cycle isn't possible (no monitor can display at 100,000FPS) but a live view would be possible, I will add it as an issue.  The only other functionality mentioned here is highlight-on-changes, which is already an issue, so I will close this issue for now.  Thanks for the feedback.
