### ISSUE TITLE
[1.7.2]Crash when having multiple code views

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#109]
DevKit crashes if you several code views openned, and try to create a new file, open existing file, or start debugging.

How to reproduce:
1) Open DevKit 1.7.2
2) File -> New -> Solution -> "NewSolution" -> OK
3) File -> New -> Project -> "NewProject" -> OK
4) File -> New -> File -> "untitled.10c" ->OK
5) File -> New -> File -> "untitled-1.10c" ->OK
6) Drag the "untitled.10c" to the left, and place it like this:
![](http://i.imgur.com/2gYFw.jpg)
7) File -> New -> File -> "untitled-2.10c" ->OK
8) This dialog appears:
![](http://i.imgur.com/621Hw.jpg)
(Translation from Russian: "This element already has logical parent object. Element should be separated from the parent object before adding it to a new parent object.")

**Comment by kierenj** [comment]
Thanks very much for providing all of that detail.  This is fixed for the next release :)
