### ISSUE TITLE
Option to change Build Action on a file (build, exclude,..)

### ISSUE THREAD

**Issue by astromechza** [kierenj/0x10c-DevKit#113]
It would be really useful to be able to exclude a file from being compiled into the final bin. At the moment you have to physically delete file from the project and then add it again when you need it. A little option on the right click would be great.

**Comment by kierenj** [comment]
There is now an option to remove a file from a project (without deleting).. is that what you had in mind?

**Comment by ghost** [comment]
Maybe the ability to make a file not compile, but still show up in the project, an example would be a text document with a todo list, or a section of code only used for debugging, but you would want to not include it in the release.

**Comment by astromechza** [comment]
Well the actual need was for in the event that we can import a bulk
set of files for example a device driver library, we can choose which
ones we want to build into the project and which ones must be left
out.

**Comment by kierenj** [comment]
OK I see, for now you can remove a file from a project without deleting, but changing the so-called 'Build action' on a project will handle this.  I will just edit the title so I can remember my thoughts. Thanks :)
