### ISSUE TITLE
move/delete cdisk file causes crash

### ISSUE THREAD

**Issue by Acruid** [kierenj/0x10c-DevKit#114]
If the HMD2043 plugin cannot find a 10cdisk file that has been made, it crashes when it is loaded.

Steps to reproduce:
1. Open the Devkit.
2. Go to the "configure disks" window of the HMD2043 plugin, and create a new disk.
3. Unload the HMD2043 plugin.
4. In Windows explorer, delete/move the 10cdisk file.
5. Back in the Devkit, load the HMD2043 plugin.

Also, the 10cdisk file is not being deleted/unregistered when the "Remove" button is pressed, so the next time the HMD2043 plugin is loaded, this error show up. This effectively prevents 10cdisk files from being moved or deleted once created.

**Comment by kierenj** [comment]
Fixed for the next release, thanks for the feedback
