### ISSUE TITLE
Cannot set breakpoint at address 0

### ISSUE THREAD

**Issue by tyrel** [kierenj/0x10c-DevKit#115]
The first instruction of my program is HWN Z. If I set a breakpoint here, and click the run button, the breakpoint does not get hit. However if I set the breakpoint to the next instruction (SET I, 0 in this case), it does get hit when I run.

I also noticed this happens if I set the breakpoint at the very beginning of my interrupt handler (the address in IA). It doesn't get hit, but a breakpoint on the following line does. It doesn't seem to matter what instruction is there.

I noticed this on 1.7.2 and 1.7.3.

**Comment by kierenj** [comment]
The breakpoint list is checked after each instruction is run, rather than before.  This will be resolved for the next release, thanks for the feedback!:)

**Comment by kierenj** [comment]
Fixed for the next release: you can now set a breakpoint at 0000, or the first instruction of the interrupt handler (not possible before!)
