### ISSUE TITLE
Breakpoints after IF* don't work as expected

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#118]
If you set breakpoint on the instruction after `IF*`, breakpoint will be triggered even if that command isn't executed.

How to reproduce:
1) Start DevKit.
2) Create new solution, project and file.
3) Write this code:

``` dasm
SET A, 1
IFE 0, 1       ; always false
    SET A, 2   ; set breakpoint here
SET B, B       ; nop
SUB PC, 1
```

4) Set breakpoint on the 3rd line.
5) Run the program.
6) It stops at the breakpoint.

**Comment by kierenj** [comment]
Thanks, will take a look into this as a priority

**Comment by kierenj** [comment]
Fixed for the next release, thanks for the feedback!
