### ISSUE TITLE
Feature Request: Code navigation (symbol list, and per-file dropdown)

### ISSUE THREAD

**Issue by booyaa** [kierenj/0x10c-DevKit#119]
Can you a drop down to jump to a specific part of code by label?

**Comment by kierenj** [comment]
This is kind of on the todo list, as a 'symbols list'.  I wanted to wait for someone to ask before actioning it, to make sure it would be used.  So, thanks for the feedback :)  It's planned

**Comment by Bobbias** [comment]
Yes, this would definitely be handy, especially for writing larger projects.

**Comment by kierenj** [comment]
Next release has full symbols list explorer pane and a dropdown with all symbols for each file.  It's great to be honest :)  Anyway, implemented for next release
