### ISSUE TITLE
Documentation : How do multiple files work together in a project?

### ISSUE THREAD

**Issue by booyaa** [kierenj/0x10c-DevKit#120]
When ever I add a new file to a project I can never get it to run. Only first file/code created in the project seems to run.

**Comment by kierenj** [comment]
Hi, that's odd :)  They should all be compiled as if they were concatenated into one big file (kind of).  If you have labels, macros in other files you can refer to them, and if you have code in two files, so long as the code would flow from one to the next (no stop/loop at the end of one), execution will run into the next.  If you like, I can take a look at a simple example problem you're having and advise.

**Comment by booyaa** [comment]
ah so that's how it works! sorry misunderstood it's use!
