### ISSUE TITLE
"Internal compiler exception generating binary output" bug

### ISSUE THREAD

**Issue by astromechza** [kierenj/0x10c-DevKit#121]
Keep getting this error is a large project and without any better explanation its proving impossible to track down:

```
Error | Internal compiler exception generating binary output: Index was outside the bounds of the array. | (none) | 0
```

Have a feeling its a label problem but I have no idea how or where to fix it.

**Comment by kierenj** [comment]
Ack, I would love to solve that one.  Is it possible to send me your solution, or a cut down part of it which has the error?  Would be treated with complete confidence.

**Comment by astromechza** [comment]
Ok this error turned out to be caused by: "JSR [B+0]"
It seems to not like the +0, as other numbers work fine.

Another coder said he got the same error from "HWI, I"   (comma in the middle)

Hopefully this helps.

**Comment by kierenj** [comment]
Ah great thanks!  I had never had anything evaluate to register-plus-zero-literal before.  JSR [B+0] now assembles as JSR [B].  Fixed for the next release.

For `HWI, I`: it seems to give a better/different set of error messages, "Invalid list element expression", which is what I would expect.  If there's a problem there best to have another issue raised as a bug.
