### ISSUE TITLE
Way to Access the Heap?

### ISSUE THREAD

**Issue by CannibalVox** [kierenj/0x10c-DevKit#124]
Ordinarily if I need access to the beginning of the heap, I can drop a label at the end of my code file and use that.  With the multi-file setup of DevKit, it's not entirely clear to me how to grab the memory address of the end of my program memory.

**Comment by kierenj** [comment]
Hi - currently all projects are built in order, and all files within projects are built in order.  That means the first file of the first project is compiled to 0000, and the end of the last file of the last project marks the end of compiled output (and start of the 'heap' if you like).  There are a few things planned so the memory map can be 'built' and the build order/specification of output is more obvious.  I hope that answers your question for now?

**Comment by CannibalVox** [comment]
This should be fine- so I can add a project at the end of the solution with a single file that marks the heap, I guess?

**Comment by Acruid** [comment]
Yes, you can.

**Comment by CannibalVox** [comment]
Thanks for the response!  I'm gonna close this since it's all I need, sorry if that's wrong.
