### ISSUE TITLE
Basic right click menu options on the code window

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#125]
Basic cut, copy, paste options on a right click menu in the code window, I know there's hot keys, but still, I'm sure it trips people up when they go for it and it's not there. Extra credit: It would be neat to be able to right click a constant, or label, and then have the ability to jump to it's equivalent line(if it has one) from the right click menu

**Comment by kierenj** [comment]
Yes, this has been lacking since the switch to the new editor control.  Thanks for the feedback, will implement!

**Comment by kierenj** [comment]
Implemented for the next release :)
