### ISSUE TITLE
Dcpu network simulation

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#134]
The basic idea is letting code in different files run on different dcpu's and letting them interact as if they were connected to each other like hardware. It's not something that would be easy to do, but it would be very cool to have them interact and simulate hardware

**Comment by kierenj** [comment]
Its easy enough, but there is no hardware to connect them, which is a problem!  If a modem or comms spec is available from Notch or is hinted at, it will br jumped on :)

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Dcpu network simulation (#134) 
From: DarkChowder reply@reply.github.com 
To: Kieren Johnstone kierenj@gmail.com 
CC:  

The basic idea is letting code in different files run on different dcpu's and letting them interact as if they were connected to each other like hardware. It's not something that would be easy to do, but it would be very cool to have them interact and simulate hardware

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/134

**Comment by kierenj** [comment]
When the network spec is announced (sounds like it might be soon), a new issue will be created.  I'm culling the list a little now to get an accurate idea of what is planned/in progress.
