### ISSUE TITLE
Stepping instructions in disassembly

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#135]
When I have the disassembly window open and I step an instruction in my program, the most obvious action in my opinion is that it would stay in disassembly view and just highlight the next step there, but as of 1.7.3 the behavior seems to be to switch to the source file of the current instruction instead (or crash if it can't find it). I would prefer this either to happen automatically when I am already in this view, or at least let there be a proper option to stay in disassembly view when stepping.

**Comment by kierenj** [comment]
I agree.  Will certainly have it keep to the disasm view in that situation.  As a workaround in the meantime you can drag the Disasm tab to another window/location and it won't disappear.

**Comment by kierenj** [comment]
Now implemented for the next release, thanks for the feedback :)
