### ISSUE TITLE
Line ending character

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#138]
It's nice to have a character that can be used instead of a  new line

**Comment by kierenj** [comment]
This would be possible by modifying the tokeniser - what did you have in mind? Underscore perhaps?

**Comment by ghost** [comment]
Maybe one of these suckers? "|" , the obvious choice the semi-colon has been used as a comment for some forsaken reason.

**Comment by kierenj** [comment]
Not currently implemented, but | should be a bitwise OR.  I think _ is used in some languages, or a backslash ().  It might also be possible to attempt to detect the end of a line/expression in the parser code, meaning you don't have to use a character.  I'm going to revisit this at some point soon to see if there are any more comments/thoughts

**Comment by ghost** [comment]
You could in fact make the space the end of line character, because the format is very straight forward

**Comment by kierenj** [comment]
Technically, space or a pipe (| or ¦) cannot work as alternative line-ending characters.  I'm going to close this one for now..
