### ISSUE TITLE
Global solution options including output formats

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#139]
Exporting a project as a memory dump, hex, plain assembly, executable, and other formats. Especially the plain assembly, because I would like to be able to see what it's doing to my code, and to copy, paste it into the real thing some day! I was looking in the project folder, and you already do a some of this, so just adding an export option would complete a few of those.

**Comment by kierenj** [comment]
Hope you don't mind, Ive altered this slightly - right-click options on a Solution would give you some options including which output formats should be produced when building.

**Comment by ghost** [comment]
Yeah that is fine.

**Comment by kierenj** [comment]
This is made redundant by the cool new project system - for Code projects you can choose which output files to produce, and customise compilation options (like producing self-relocating code etc).
