### ISSUE TITLE
Arrow keycodes

### ISSUE THREAD

**Issue by tomix1024** [kierenj/0x10c-DevKit#142]
The arrow keys aren't working in my program.
If I press up for example there should be a keydown event for the key number 0x80 but there isn't!
The same thing for the other arrowkeys as well.

**Comment by kierenj** [comment]
Please see here, official specs and emulator indicate that DevKit is working correctly: https://github.com/kierenj/0x10c-DevKit/issues/108 - I will close this issue but if you still think it's wrong, give a breakdown of the way it's happening differently in the official (RC1) emu and open another please :)
