### ISSUE TITLE
Remove Invalid Recent Solutions

### ISSUE THREAD

**Issue by Acruid** [kierenj/0x10c-DevKit#144]
When you click on a recent solution in the file menu that does not exist, the dialog box should give you the option to remove it from the list.

**Comment by kierenj** [comment]
This is already the behavior in the app (just tested).  It's just the start page that doesn't get updated until you re-start.  Is that the problem you are having too?

**Comment by kierenj** [comment]
Ah, I found another bug in there, so it wouldn't have always worked.  Fixed now, thanks!

**Comment by Acruid** [comment]
So it turns out this was a bug. I will wait until the next release to see if whatever you found fixed it, and then open another issue if needed.
