### ISSUE TITLE
[reg+0] assembles to [reg], but still appends 0x0000

### ISSUE THREAD

**Issue by dekay9001** [kierenj/0x10c-DevKit#146]
When you do something like this:

add [a+0], 1

it will be assembled to

add [a], 1
dat 0x0000

in 1.7.3 it was assembled with a literal value 0x0000, in 1.7.4,
the generated opcode was changed, but the literal value still persists.

**Comment by kierenj** [comment]
Thanks for flagging this, it's pretty crucial!  I've now got a test case of about 70 opcode/operand combinations with various literals, labels etc, and am re-checking them all.

**Comment by kierenj** [comment]
Sorted for the next release.  Thanks for the feedback, this was a nasty one.!

**Comment by dekay9001** [comment]
I'm happy i could help, and thanks for fixing!
