### ISSUE TITLE
C compiler requires MSVCP100D.dll

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#147]
When compiling C code in 0x10c-devkit, _dtcc.exe_ won't complete because it can't find MSVCP100D.dll (this is the _debug_ version of the Microsoft Visual C++ 2010 runtime, which won't be available on most users' computers [[source](http://stackoverflow.com/a/6580733)]).

**Comment by kierenj** [comment]
Thanks for reporting this.  Fixed for the next release -this .dll and another are added:)
