### ISSUE TITLE
directives

### ISSUE THREAD

**Issue by rustyoz** [kierenj/0x10c-DevKit#149]
is there a list of directives that devkit supports?
or just documentation in general

**Comment by kierenj** [comment]
Hi, there is a manual section on the website which outlines the basics.  What can I help you with specifically?

**Comment by rustyoz** [comment]
i was trying to get atlas to compile correctly in dev kit. 
currently we use "organic" to compile it to a bin. 
with the include directive you can for example:

code blah blah
...
#include "drivers.dasm16"
code blah blah....

now this will compile drivers.dasm16 to hex, add it to what is already compiled and then continue on. 

from what i understand now, there is no way to do that in devkit. 
the issue being, with the above example it is easy to specify where code will be complied to within the memory space. 
we have for instance a defined block of dat null to specific where the api will go

how does devkit handle code segmented into other files?

**Comment by kierenj** [comment]
Ah I see.  You cannot #include, instead you should add the file to a project.   Files are compiled into memory in the order the projects, and files within them, appear.  There is a feature outstanding to be able to re-order the files/projects and the order they appear, but other new features and spec improvements have been more requested.  The best bet is to create a project, then add files to it in the order you want to see them compiled.

The next chunk of work planned relates to exactly this - 'designing' build output, where code is compiled to etc.  Let me know if I can be of any further help.

**Comment by rustyoz** [comment]
ah ok that makes sense. i just have to split a file or 2 up. thanks

**Comment by kierenj** [comment]
Great.  Please get in touch if I can help - I will close this issue for now.
