### ISSUE TITLE
er.. DAT not working?

### ISSUE THREAD

**Issue by darktr-zz-ace** [kierenj/0x10c-DevKit#15]
Tried the helloWorld example to test the IDE. Everything works great except the DAT instruction kept throwing ExpressionEndOfStream and ExpectedDataExpression

:message 
    dat "Hello, World!", 0

**Comment by Mause** [comment]
Had the same problem, added a newline afterwards and worked fine.

**Comment by kierenj** [comment]
This is a known bug - the final line of code in a file needs to end in a newline.   Will be fixed inthe next release. Thanks for the feedback!

Thanks
Kieren
