### ISSUE TITLE
Saving Read-only File Crash

### ISSUE THREAD

**Issue by Acruid** [kierenj/0x10c-DevKit#151]
The Devkit will crash when trying to save to any read-only file. This includes all types of code files, the 10cproj files, and the .10csln file. It crashes when trying to save to a file with the attributes set to read-only, and writing to a file when the program does not have write permissions from UAC (such as the contents of C:\Program Files).

**Comment by Acruid** [comment]
Also, if you delete the solution folder while the solution is open in devkit, and then close the solution through the file menu, the Devkit will crash from not being able to access the .10csuo file. This is probably from the same bug.

**Comment by kierenj** [comment]
It's a general issue that exceptions when saving aren't reported.  Thanks for continuing to find and report these bugs :)

**Comment by kierenj** [comment]
Fixed for the next release, thanks
