### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#155]
I want a debugging tool that instead of breaking outputs something like this to the console

The value in register A was 1 instead of 0

And to make it output this, you could make a special comment like this

;~"The value in register A was [A] instead of 0"

So instead of breaking, it just outputs the message when the line is reached.
This will allow easier testing if there is no monitor, or for a quick example to avoid the additional overhead of a monitor.

**Comment by kierenj** [comment]
The upcoming Debugger virtual hardware device will allow string output, or word output, which I think may wrap this up?  I will close for now, you are welcome to comment or re-open if it doesn't do what you want when you've tried it, if that's agreeable :)
