### ISSUE TITLE
DIV error with EX

### ISSUE THREAD

**Issue by kirinyaga** [kierenj/0x10c-DevKit#159]
In following code :
        SET A, 0xFF00
        SET B, 0xFF87
        DIV A, B
EX should be FF78 (=(FF000000 / FF87) & FFFF), but it is FF00.

**Comment by kirinyaga** [comment]
Additional info : 
DIV 7FFF/FF87 works fine
DIV 8000/FF87 does not (7FC4 in EX instead of 803C)
Probably a signed/unsigned mismatch : 80000000/0000FF87 (signed) is indeed FFFF7FC4.

**Comment by kierenj** [comment]
All fixed and unit-tested for the next release:)
