### ISSUE TITLE
Stuck when building AtlasOS

### ISSUE THREAD

**Issue by noxer** [kierenj/0x10c-DevKit#16]
When building AtlasOS 0.5.3 DevKit does... nothing.

All I see in Build Output is:

[14:26] Ready
[14:26] Building solution...

I waited several minutes now but nothing happens (and my CPU idles).

**Comment by kierenj** [comment]
We will investigate further, thanks for the feedback!

**Comment by kierenj** [comment]
For information: This is because label references are (were) not supported in 'data instructions' (dat directive).  Fix in progress now.

**Comment by kierenj** [comment]
In the latest build (not yet available), AtlasOS builds.  But it uses nonstandard keyboard IO (not a circular buffer) and depends on the screen text size being non-standard too (an extra 4 lines, in contradiction of current specs).  Thanks for the input and help getting to this point - as it stands however, AtlasOS will not run as it depends on emulator-specific differences.

**Comment by noxer** [comment]
Thats why I was trying to run it in DevKit ;). I'm working on a new keyboard driver.
Thank you!

**Comment by kierenj** [comment]
Ah fantastic.  Would love to assist in getting it all going in DevKit.  New release should help things along - I was able to fix by temporarily having it work in the obscure keyboard IO method (just 0x9000) and reducing the end of VRAM from 0x8200 to 0x8180.  Hope to wrap up a few more bits of feedback and bugs, could be a few days.

**Comment by rustyoz** [comment]
i have also tried to run AtlasOS in the devkit

it comes up with a Cannot modify operand error when compiling. 
the problem code is:
:page_find_free_found_loop
      SHR PEEK, 1 

considering that atlas seems to work when this error doesn't seem to come up in other emulators, i think this is an error in the compiler

**Comment by kierenj** [comment]
Yes indeed and thanks for the feedback, this issue was closed yesterday as fixed in the current build however, which means the fix will make it into the next release.
