### ISSUE TITLE
disk example code

### ISSUE THREAD

**Issue by rustyoz** [kierenj/0x10c-DevKit#161]
I am having trouble using the disk plugin

do you have some example assembly code using the plugin?

**Comment by kierenj** [comment]
Hi, there's no devkit specific example but it should implement the standard if you wanted to look for some code online.  If there's a specific problem or question I may be able to help though?

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] disk example code (#161) 
From: bungao reply@reply.github.com 
To: Kieren Johnstone kierenj@gmail.com 
CC:  

I am having trouble using the disk plugin

do you have some example assembly code using the plugin?

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/161

**Comment by rustyoz** [comment]
does devkit make a temporary disk file named after the solution?

**Comment by kierenj** [comment]
Yes, it does currently
