### ISSUE TITLE
HMD bug

### ISSUE THREAD

**Issue by rustyoz** [kierenj/0x10c-DevKit#165]
After a solution is built it creates a disk file under the solution file name, 
i have found that this disk starts with some section of the memory already written to the disk even before it has been accessed by the emulated DCPU

**Comment by kierenj** [comment]
Yes, as described in the latest video, in order to get people playing with the disks, a disk is generated with the contents of the solution.  The next release will feature 'Disk projects', allowing you to build up a disk image with code/data.
