### ISSUE TITLE
Unable to shift on PEEK

### ISSUE THREAD

**Issue by noxer** [kierenj/0x10c-DevKit#17]
According to Notch PEEK should translate to [SP]. But in DevKit SHR complains about PEEK as destination:

SHR PEEK, 1

**Comment by kierenj** [comment]
PUSH and POP as shorthand were added just before the release (in fact, while testing Tetris).  PEEK is certainly one we need to correct for.  Thanks for the feedback!

**Comment by kierenj** [comment]
Implemented for the next release
