### ISSUE TITLE
Multiple device support

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#173]
There will be support for multiple devices on the original dcpu.
I request a separation of plugins(plugins for devkit), and devices(hardware for dcpu).
The new device drop down, would have the options of Add , Remove , and Configure Device.

**Comment by kierenj** [comment]
Indeed I had the same thought - a Device Registry.  Plugins register a 'class' of device, and then you can configure your setup, # of devices etc, as required.

**Comment by kierenj** [comment]
Implemented for 1.7.6 with per-solution "Loadouts"
