### ISSUE TITLE
Vector display won't unload

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#176]
If I try to unload the vector display after loading (or auto-loading), it will still be visible in the display window (although not recognized as a connected device by the emulator). If I try to reload it after unloading, I will see two vector displays in the display window, with only the rightmost being active and usable.

**Comment by kierenj** [comment]
Thanks for the feedback, this should be a bit neater!

**Comment by kierenj** [comment]
This is now fixed, thanks. :)
