### ISSUE TITLE
DevKit is not backwards compatible with 1.7.4

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#179]
Projects created with DevKit 1.7.4 will not work with 1.7.5
Non-converted files will get stuck at Building Solution, and eventually crash.

The crash is being caused by the lack of property files in the 10cproj, and 10csln files.

I recommend DevKit automatically adds in the default properties to the 1.7.4 files affected, when they are loaded.
Defaults to fall back on when there not specified would also work as a solution.

**Comment by kierenj** [comment]
Hum, the changes should have been backwards-compatible, but I'll admit I didn't try more than one simple example.  Missing properties should default to.. well the default value :)  References wouldn't exist, but the whole thing should operate.  I'll look into it, thanks :)

**Comment by kierenj** [comment]
Actioned, thanks
