### ISSUE TITLE
About popup typo

### ISSUE THREAD

**Issue by Mause** [kierenj/0x10c-DevKit#18]
Typo in the about popup: http://0x10c-devkit.com/media/220/welcome.png
"guarUnteed" =/= "guarAnteed"

**Comment by kierenj** [comment]
Thanks for the feedback - fixed for the next release :)

**Comment by Mause** [comment]
Awesome :)

On Mon, Apr 16, 2012 at 12:45 AM, kierenj <
reply@reply.github.com

> wrote:
> 
> Thanks for the feedback - fixed for the next release :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kierenj/0x10c-DevKit/issues/18#issuecomment-5140439

## 

Dominic May
