### ISSUE TITLE
add spherical coordinates mode for vector display

### ISSUE THREAD

**Issue by kirinyaga** [kierenj/0x10c-DevKit#180]
That is heading (angle around vertical axis), elevation (angle from horizontal plane) and distance.
First, this will allow to easily draw circular arcs (when changing angles without changing the distance) which are likely to be needed in 0x10c for planets, stars, whatever. 
Second, running any control program on DCPU without spherical coordinates as input and output will be very difficult thus I think that's what Notch may choose. I'm working since two weeks on a trigonometry library and its optimization and I can tell you that using too much of those functions could be a serious constraint.

In order to stay versatile until we know more about it, you could just add a function to switch the mode (resetting the device), changing the meaning of X,Y & Z for interrupt 3 & 4 as cartesian or spherical coordinates.

Not a priority, obviously.

**Comment by kierenj** [comment]
Eep, love that idea.  Not a priority, but very cool, and would make for flashier demos more easily ;)

**Comment by kierenj** [comment]
Actioned/implemented for next release :)
