### ISSUE TITLE
Memory Leak (C code)

### ISSUE THREAD

**Issue by felixjones** [kierenj/0x10c-DevKit#186]
I toggled a break point whilst debugging, stopped debugging, opened the documentation for the keyboard and then my machine started running incredibly slowly.

When I managed to open task manager, Devkit.IDE.exe was using a massive 6.7GB of memory.
I tried to recreate this but it sits around 102,352 to 107,556 K, so just a heads up that there's a memory leak somewhere.

The code that did this is an empty main loop int C:

int main()
{

}

EDIT: Just to add, I left the IDE in idle whilst writing this and it is now jumping up to 150,000 K region of memory usage in idle, although this might be the .NET run time messing around.

**Comment by felixjones** [comment]
I managed to recreate this doing the exact same thing, but I had to open the documentation and close it 4 or 5 times. At the moment it's using 4GB of memory.

**Comment by kierenj** [comment]
Could you try unloading (and disabling auto-load) for the vector plugin?  That's the thing I would guess is to blame?

**Comment by felixjones** [comment]
I've left it running for some time with the vector display disabled, there was no problems, with it enabled I can still recreate the leak, so your assumption seems true!

**Comment by kierenj** [comment]
Resolved for next release!
