### ISSUE TITLE
Crash when compiling previous projects

### ISSUE THREAD

**Issue by RichardLH** [kierenj/0x10c-DevKit#189]
Trying to compile previous projects fails with an exception. New projects seem to work fine. Occurs on two seperate PCs - Win7/XP. Auto crash Bug report emailed.

**Comment by kierenj** [comment]
Hi - this is fixed for the next release already; you may be able to resolve by opening project properties and checking then unchecking the output format options.

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Crash when compiling previous projects (#189) 
From: RichardLH reply@reply.github.com 
To: Kieren Johnstone kierenj@gmail.com 
CC:  

Trying to compile previous projects fails with an exception. New projects seem to work fine. Occurs on two seperate PCs - Win7/XP. Auto crash Bug report emailed.

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/189

**Comment by RichardLH** [comment]
That does it. Thanks.
