### ISSUE TITLE
jsr 0 produces a two word output

### ISSUE THREAD

**Issue by RichardLH** [kierenj/0x10c-DevKit#191]
jsr 0 (and all other short calls/jumps, etc) should generate single word instructions.

Current output is always two words.

**Comment by kierenj** [comment]
Can you confirm that's for JSR 0 and not JSR (label-name)?  Currently referencing a label will produce two-word instructions

**Comment by RichardLH** [comment]
It was 'jsr label'. I hadn't realised that you treated labels differently to constants.

**Comment by kierenj** [comment]
It could be a single word instruction, if relocatable code isn't being generated. An optimisation that's not implemented so not such a bad idea !
