### ISSUE TITLE
BUG: open button on vector display doesn't give up keyboard focus

### ISSUE THREAD

**Issue by rustyoz** [kierenj/0x10c-DevKit#197]
i pressed the open button, and then i tried to press enter with the screen focused it it opened up the large vector display again.

**Comment by chewlish** [comment]
I noticed the same thing messing around with keyboard input today.  If the open button gets focus there doesn't seem to be a way to get it back until DevKit is shut down and restarted (neither closing the viewer window nor reloading the solution will unselect the button).  I'm running DevKit v1.7.5 in Windows 7 x64.

**Comment by kierenj** [comment]
Should be resolved for the 1.7.6 release. Thanks!
