### ISSUE TITLE
DevKit IDE Problem

### ISSUE THREAD

**Issue by neogoo123** [kierenj/0x10c-DevKit#201]
When I try to run a program in the DevKit 1.7.5 It says it runs properly but the screen doesn't come up and a popup would come up saying that there was a problem and ask if I wanted to send the error report, which I did happily twice. If the code needs to be inserted then I will put it up.

**Comment by noxer** [comment]
I've experienced a bug where DevKit consumes a lot of memory (> 8 GiB) and then crashes with the "has a problem" popup after debugging code.

**Comment by kierenj** [comment]
If this problem still occurs with the new 1.7.6 release, please open a new issue - a few memory issues have been resolved in this release :) Thanks!
