### ISSUE TITLE
Invalidate memory view on run and step

### ISSUE THREAD

**Issue by senevoldsen** [kierenj/0x10c-DevKit#203]
- **Issue**
  Currently the memory view is not updated when the program is run or debugged again. 
- **How to reproduce**
  Create simple program that changes some memory. Check in memory view that it has indeed changed. Run program again but stop before writing to memory. Old data is still in memory view.
- **Expected**
  Memory view is always up to date.
- **Workaround/Interesting note**
  By checking and unchecking the "Show one character for each 8-bit byte" you can refresh the memory view.

Using 1.7.5 Beta

**Comment by kierenj** [comment]
Hi, thanks, I've taken a look but it just seems to work for me.  This program adds 1 to memory locations after the program code:

```
    set a, target
:lp
    add [a],1
    add a,1
    set pc, lp
:target
```

I run it (with memory view open).. memory view shows "0001" filling memory.  I stop it, then step into the execution, and it's reverted to 0000.

If this is still a problem with the latest release, could you reply to this?  I will close for now.  Thanks!
