### ISSUE TITLE
Problem with plugins in devkit 1.7.6

### ISSUE THREAD

**Issue by azertyfun** [kierenj/0x10c-DevKit#211]
I have a problem : in the "Plugins" menu, there is the 3 usual submenus (loaded plugins...), but they are all empty. So, when I open a solution, I have this error box : 

> Error opening soliton: Cannot apply layout: validation failed

When I go in the properties of my solution, I have this text in red :

> Validaiton failed
> Device type GenericClock was not recognised
> Device type GenericKeyboard was not recognised
> Device type LEM1802 was not recognised
> Device type SPED-3 was not recognised
> Unable to check number of screens on primary display device; type not recognised

The plugins folder of devkit right has its files into it, but it looks like devkit doesn't detect them...

**Comment by kierenj** [comment]
Ack, that's no good.

Could you try going to C:\Users\Kieren\AppData\Local\0x10cDevKit (with your username in place of Kieren), and either renaming or deleting that folder or the files in it?  They're just config files but that might prove to be a useful clue..

Sorry you're having problems with it!  Out of interest if you had a previous version, did you uninstall it first?

**Comment by qgevans** [comment]
I've got the same issue. It's a clean install, I've never tried this software before. At startup, it flashes a couple messages too quickly for me to read, then says "Finished loading 0 plugins." I deleted both configuration files as you mentioned, and the behavior is the same.

**Comment by azertyfun** [comment]
First I didn't unistalled it, because I wanted to keep it, but I unistalled it after that to attempt to correct the bug and it didn't work. After deleting files,, the problem is already present
I tried to start Devkit in compatibility and administrator mode, but it doesn't work.
I'm going to update .NET, maybe it's that ?
EDIT : It's not .NET, it says that I already have installed .NET 4.5. If it can helps, I'm on Windows 8.

**Comment by qgevans** [comment]
Ah, I just found part of the issue. When looking at the properties in Windows Explorer for each of the plugin files, there's a note at the bottom: "Security: This file came from another computer and might be blocked to help protect this computer." After opening the properties on each file individually and unblocking them, they load. Maybe a consequence of us using the built-in Windows zip implementation to extract the archive.

**Comment by kierenj** [comment]
That will be it.  Damn- that was one of the reasons I was using an installer before.  Will have to tackle that for the next release.

**Comment by azertyfun** [comment]
Ho, thanx heddwch, that's right ^^

**Comment by qgevans** [comment]
Happy to help :) And thanks for this project, kierenj. Definitely looks like the best DCPU IDE available!

**Comment by kierenj** [comment]
Implemented automatic "unblocking" for the next version - works a treat.  Thanks for finding that one guys.
