### ISSUE TITLE
Error if opening mackapar drive configuration

### ISSUE THREAD

**Issue by azertyfun** [kierenj/0x10c-DevKit#212]
Hello !
When I want to open the mackapar 3.5" floppy drive (M35FD), I have this error (this is an approximate translation, my OS is in French so I don't know if it's exactly that in English) : "Impossible to define the property Owner with an object Window who wasn't previously showed". Here's the file that the error window gave me if it can helps :
ftp://192.168.1.222/errorReport%20devkit.saencryptedreport
I have well unblocked files in my plugins/ and api/ folders. Also, when I open the LEM1802 config file, there isn't any error file, but the window doesn't appear.

**Comment by kierenj** [comment]
Thanks, found the problem, I'm fixing up the configuration screen now.

I'll remove the LEM1802 configuration option - it used to allow you to specify the number of screens, but that's irrelevant now, you can have multiple instances of devices by adding them manually to the loadout XML on the solution.

**Comment by azertyfun** [comment]
Okay, thanks and happy to help :)
But if you remove LEM1802 configuration, I think you should do something to advertise users that if they want to have multiple devices, they must modify the loadout, no ?
EDIT : also, when I replace "<primaryDisplay>LEM1802-1:1</primaryDisplay>" by "<primaryDisplay>LEM1802-1:2</primaryDisplay>", it says me a validation failed because "Primary display is invalid: not that many screens on given device" ^^

**Comment by kierenj** [comment]
Ok M35FD configuration now seems to work OK (next release).  For the other screens - LEM1802-1:2 means screen 2 of the first device.  But the devices only have one screen each, so it would be LEM1802-2:1 :)

**Comment by s-ol** [comment]
I cannot use the M35FD plugin at all.
I can load it, but like in Issue #216  the option menu doesn't work.

Further, I cannot add a M35FD to the loadout, even with the plugin loaded I get:
    `Validation failed
    Device Type M35FD was not recognized`
