### ISSUE TITLE
Cannot add to memory watch?

### ISSUE THREAD

**Issue by JeremyWildsmith** [kierenj/0x10c-DevKit#213]
In the old devkit, all you would do is select an open row on the watch window and enter an expression to watch. However, in the new devkit, there is no open row.

Is this a bug, or is there another way I should add watches.

**Comment by kierenj** [comment]
Looks to be caused by a bug in a new .NET version.. I am investigating, thanks!

**Comment by kierenj** [comment]
Nope, that's not it.. it was a leftover from some refactoring.  Fixed for next release! Thanks again.
