### ISSUE TITLE
Remember open files and currently-selected file when solution closed/re-opened

### ISSUE THREAD

**Issue by kierenj** [kierenj/0x10c-DevKit#23]

**Comment by mortware** [comment]
Added support for remembering open files and currently-selected file when solution closed/re-opened

XML file is saved alongside main solution file (a la VS)

**Comment by kierenj** [comment]
Bit of a bug - if no file is open when closing solution, there's an Exception @ this.CurrentFile.AbsolutePath

**Comment by mortware** [comment]
D'oh... I'll fix that then

**Comment by mortware** [comment]
Fixed and checked in
