### ISSUE TITLE
Cloud-based solution storage

### ISSUE THREAD

**Issue by kierenj** [kierenj/0x10c-DevKit#24]
Using username/password or Facebook auth, you could store your solutions in the cloud to access from anywhere - could even use git/integration.

**Comment by GendoIkari** [comment]
I prefer Google Api integration instead of Facebook, but it's not necessary.

**Comment by kierenj** [comment]
Removing this from the list for now, it's a future idea.  Relates to an idea for solution/project templates, self-contained, with code.. the wrapper format would be handy for this.  But, not now .. :)
