### ISSUE TITLE
When typing characters in code editor, it flashes the whole window (intermittent)

### ISSUE THREAD

**Issue by mortware** [kierenj/0x10c-DevKit#37]
Reported on the forums by CX

http://www.0x10cforum.com/forum/page/3/m/4932880/viewthread/2803536-0x10c-development-kit-beta-1-release

Video demonstrating the problem.
http://youtu.be/Vgpu0uB9b4s

**Comment by Acruid** [comment]
I also have the same issue.

You can see the issue throughout the tutorial video that Team Chicken posted on youtube.
http://www.youtube.com/watch?v=bEkC-bcNESw (20:00 in)

**Comment by kierenj** [comment]
I'm looking into replacing the component used for the text editor control now

**Comment by kierenj** [comment]
New component is great - fixed for next release!
