### ISSUE TITLE
Macroses

### ISSUE THREAD

**Issue by Zibx** [kierenj/0x10c-DevKit#38]
I really want them being accessible from all files. Or from files with some macros extension (divide them from asm files).
Also it would be great if you connect some language for writing macroses. I would like to use cycles and conditions in macros generation, So I would be able to do this:

``` js
jsMacro Test = function( a ){
  var out = 'set b, a\n';
  for( var i = 0; i < 32; i++)
    out += 'set [b+'+ i +'], 15\n'
 return out;
}
```

(if language is js, you can take any language for macroses like java, c, it would be really great). After macros generates ssource - you should take it and parse with your engine to resolve, for example, math in adresses.

**Comment by astromechza** [comment]
Another question about macros: How does devkit assemble them? If i use a macro often does it assemble the code at each location every time or assemble the macro once and link to it?

**Comment by kierenj** [comment]
That's precisely right: a macro is a piece of code generated each time you use it (that's the difference between a macro and a function/subroutine).  This macro feature (Zibx's suggestion) is slightly different, and refers to code generation.  This is not a feature the DevKit needs desperately and I would actually suggest someone writes a plugin to do it, if they feel it's important ..
