### ISSUE TITLE
Source???

### ISSUE THREAD

**Issue by startling** [kierenj/0x10c-DevKit#39]
I'm confused; all I see is a readme and some binaries. I think you forgot to push?

**Comment by norswap** [comment]
Is the devkit open source ? If not, why ?

**Comment by kierenj** [comment]
The source code is not currently available, thanks for your interest.

Thanks
Kieren

**Comment by ghost** [comment]
github is, unfortunately for you, a source-sharing community. If you are unwilling to share source code, it would appreciated if you did not abuse the services that github provides by finding a different host for your binary files. 

Thanks
Miles

**Comment by kierenj** [comment]
It provides many excellent services of course, and I am/was not aware of any terms of use indicting that any use must include full source code.  Thanks for indicating this, I will investigate fully.  The intention is to release an API for plugins for languages and peripherals - as indicated on the site - but if this is inappropriate we may have to switch to another service as you indicate.

Thanks
Kieren

**Comment by norswap** [comment]
Github is free only for open source projects, as can be seen on the pricing page: https://github.com/plans (you need to logoff to view the "Free for open source" line). If you are a paid user however, it's perfectly fine to be closed source.

**Comment by kierenj** [comment]
I was not aware of that, and will get right onto that this evening when I'm back at a PC.  Thanks for the info

Thanks
Kieren

**Comment by kierenj** [comment]
I am clarifying with GitHub support and will update this issue accordingly.

**Comment by kierenj** [comment]
I still haven't heard back from GitHub support, and was unable to find anything explicit in the Terms of Use.  I will keep this issue open until I hear back from them.

**Comment by kierenj** [comment]
This just received from GitHub support (first line is my question).  I'm going to close this issue based on this.

> People have suggested that it's not allowable to use GitHub just for
> downloads and issues on a non-open-source project. Is this the case? - If
> so, what plan do I need?

I use GitHub for knitting patterns. I don't think anything you're doing breaks our Terms of Service. You can always read them over if you're feeling nervous, but nothing says you have to have code in your repo.
http://help.github.com/terms-of-service/

Cheers,
Sonya

**Comment by ghost** [comment]
Well I think you'll find that on the github website it says 'Free for open
source projects'. This isn't open source.

On Fri, Apr 27, 2012 at 6:11 PM, kierenj <
reply@reply.github.com

**Comment by kierenj** [comment]
If you would like to take this further, I suggest you speak with GitHub support (who advised me directly on the issue).  I would guess that they are the definitive source in this regard, rather than yourself.

**Comment by norswap** [comment]
No need to pester the guy. I prefer open source myself, and I still hope this project can become just that. But GitHub support is clearly ok with this.

Btw I'd like to make clear my intent was never to have the "evil closed-source project" put down, but rather to inquire about open source plans and inform you of what I thought the policy was, since having one's account closed without notice is always a bitter experience.

**Comment by ghost** [comment]
kierenj: Can you read? It says 'Free for open source projects'. You're hosting binaries without posting source.

**Comment by kierenj** [comment]
I implore you, write a letter to your representative, start a community movement, threaten me with legal action, pester GitHub support. Whatever you feel you need to do.  Have a good weekend.

**Comment by kierenj** [comment]
I'm going to be honest, I have found a few people's response to making a fully-featured product that has taken many hours of work available for free, pretty rude and presumptuous.  It's free already, and while open source has advantages, right now the project is not open source and it really doesn't matter why.  I'm sorry if you don't support the project, but I also really don't mind if you choose not to.

However, as I'm sure you have seen there's a very quick turnaround of bugs and features and spec changes, and very regular releases.  If you'd like to suggest a feature and it fits with the feel and general direction of the project, it would probably make it in.  An IDE option to zoom code or change font sizes would be fairly straightforward and would certainly be something that we would want to include.  Raise an issue if you would like.
