### ISSUE TITLE
Basic functionality broken

### ISSUE THREAD

**Issue by Zibx** [kierenj/0x10c-DevKit#40]
Sometimes I have strange things.
In loop I set a to [fullScreen] two times and call draw. In first case it don't set really [fullScreen], but some shit. In second case it sets a normally. If I view in expression viewer [fullScreen] in two cases - it gives same normal value.
Also I push\pop all registers in functions, but If I call some function two times - it brokes all, but one time is ok. There is some floating bugs with basic memory work.

**Comment by kierenj** [comment]
Please could you link or attach your solution folder and all source, we will investigate.  If you can, provide the very least amount of code possible to show off any bug.

Thanks
Kieren

**Comment by Zibx** [comment]
I've sent it via 0x10c forum, but I think maybe it's another problem than I describer. Maybe IDE should notice when we are at the adress that don't corresponds with normal command offset.

**Comment by kierenj** [comment]
Hi Zibx, could you see if the latest released fixed this please?  There were several improvements and bugfixes, and I'd love to hear if everything is working well now.

**Comment by kierenj** [comment]
If this issue still persists, or happens again, please respond to this issue.  In the meantime, I'm going to close it off
