### ISSUE TITLE
[1.3]Error at line 0 in file "(none)"

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#49]
![Error](http://i.imgur.com/eE0Fr.jpg)

**Comment by kierenj** [comment]
This message should appear if you do something like "set pop, a" or "set [sp++], b".  Can you supply any code that causes this error mistakenly please?

**Comment by ghost** [comment]
``` dasm
;line 1
set pop, A ;line 2
;line 3
```

The error _should_ be thrown. The problem is that it says that error was in file "(none)" on line 0. But it was in file "main.10c" on line 2

**Comment by kierenj** [comment]
Ah great: thanks, the system passes expressions through the compilation system as long as possible so only the final code generation pass validates combinations of operands.  This will be tidied up for the next release, thanks :)

**Comment by kierenj** [comment]
The tokeniser, parser and compiler were all using 'nice' errors, but the code generation phase was relying on exceptions.  This is no longer the case, and all invalid instructions or errors have greatly improved error messages, for the next release.  Thanks for the feedback :)
