### ISSUE TITLE
Hello World sample displays only black screen.

### ISSUE THREAD

**Issue by Radar11x** [kierenj/0x10c-DevKit#59]
I copied the sample for hello world but only get a black screen in 1.1 and 1.3 but the code seems to work fine in 1.0 with the text and blue screen displayed.

**Comment by kierenj** [comment]
Hi - the system specs have changed a lot since the earlier versions - the manual sample will have to be updated (it will be).  Thanks for the feedback!

**Comment by Bobbias** [comment]
I'm writing a hello world program right now. If you want you could use it for the example (I'm using the latest release).

**Comment by kierenj** [comment]
Added disclaimer messages to Manual; we don't know how much more the CPU/peripheral specs might change.  When they stabilise, we'll add new examples.
