### ISSUE TITLE
Syntax highlighting: semi-colons in string literals

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#60]
When using semi-colons in a string literal in `DAT` segment, everything after the semi-colon as if it was a comment, though the code would run as expected (with the semi-colon being treated as a literal character and not a comment marker).

![Screenshot](http://i.imgur.com/wmQoO.png)

**Comment by kierenj** [comment]
All fixed for the next release, thanks for the feedback:)
