### ISSUE TITLE
RFI not recognized

### ISSUE THREAD

**Issue by BenSheftel** [kierenj/0x10c-DevKit#62]
The RFI opcode added in http://pastebin.com/raw.php?i=Q4JvQvnM (spec 1.7) isn't recognized in the DevKit 1.7 preview release, instead giving this error:

Error   UnableToResolveMacroName    Unable to resolve macro name

**Comment by kierenj** [comment]
I just double-checked (and triple-checked): it is recognised.   Please check you are using 1.7 and post your code if you still have a problem!

**Comment by kierenj** [comment]
(Let me know if I can close this off, please ;))

**Comment by BenSheftel** [comment]
Huh, closing and opening DevKit did the trick.
