### ISSUE TITLE
black on white text, bug

### ISSUE THREAD

**Issue by astromechza** [kierenj/0x10c-DevKit#69]
Devkit does not seem to support black test on white background eg: 0x0F4D   should be black text on white "A"?

**Comment by astromechza** [comment]
or rather 0x0F41

**Comment by kierenj** [comment]
Correct, this is a bug, will investigate, thanks!

**Comment by kierenj** [comment]
Found and fixed for the next release. Sorry for the inconvenience, will be usable again soon.  This is a real pain, will be trying to set up automated development builds so people don't have to wait very long to see fixes.
