### ISSUE TITLE
Feature request: unit tests

### ISSUE THREAD

**Issue by GendoIkari** [kierenj/0x10c-DevKit#73]
I know this is not the highest priority at the moment, but it would be wonderful to have a simply way inside the IDE to run a test suite. Something like:
File -> New -> Test Suite

To define test some custom directive like:

```
#test MyUnitTest
    set a, 0x1
    set b, 0x1
    #assertEqual 0x2, a
    set pc, pop
```

Than:
Build -> Run Test Suite

And have some usefull output like:

```
.....F.....
xx test executed.
1 failed.

MyUnitTest: line 3, "#assertEqual 0x2, a"
    0x2 expected but was 0x1
...
```

I think unit test support will made this SDK pretty professional (and effective).

**Comment by kierenj** [comment]
Great idea, the DevKit itself has unit tests, but it only checks that a set of standard assembly files compile correctly.  I imagine this would involve extended the RuntimeEngine with a breakpoint and dynamic expression evaluation on #assertEqual.  Actually not too difficult!  These would likely be in the form of .10ctest files with a custom build action (different file types and corresponding modular build are in the planning phase)

**Comment by kierenj** [comment]
This is in progress, and uses a new virtual hardware device (Debugger) rather than language constructs :)

**Comment by kierenj** [comment]
Unit tests are in, and looking great.
