### ISSUE TITLE
Closing the display while emulating forces main window behind other programs

### ISSUE THREAD

**Issue by Bobbias** [kierenj/0x10c-DevKit#74]

**Comment by GendoIkari** [comment]
Reproduced with Devkit-1.7-Beta-Preview-NoInstaller.zip

**Comment by Bobbias** [comment]
I noticed that it only happened when you click the yes. I hit enter instead and it didn't force the window back.

**Comment by henrikp** [comment]
Reporting the same issue, but it doesn't matter if I click or press enter. Running XP SP3.

**Comment by kierenj** [comment]
Thanks for the feedback guys, this is now fixed for the next release :)
