### ISSUE TITLE
Font Colours Bug

### ISSUE THREAD

**Issue by astromechza** [kierenj/0x10c-DevKit#75]
I know I listed the black font error but there seem to be other problems with font pallets.

Running the code:
    SET [0x9000], 0x214C
    SET [0x9001], 0x224C
    SET [0x9002], 0x234C
    SET [0x9003], 0x244C
Where my lem1802 is mapped to 0x9000 onwards.

It should output 4 "L"'s all in a blue foreground with different background colors but instead it changes the foreground colour as well as the background colour.
![screenshot](http://i1242.photobucket.com/albums/gg534/AstromechZA/s.jpg)

**Comment by astromechza** [comment]
Checked with notch's rc_1 LEM1802:
The L's should all be the light green color, (0,170,0)

**Comment by kierenj** [comment]
Yes correct, this is a dupe however, already fixed:)

**Comment by astromechza** [comment]
Ah so sorry.
