### ISSUE TITLE
Possible Building Bug

### ISSUE THREAD

**Issue by GendoIkari** [kierenj/0x10c-DevKit#76]
Have fun with this code xD

```
; --------------------------------------------
; Title:   Infinite Building Bug
; Author:  gendo
; Date:    29/04/2012
; Reproduced with: Devkit-1.7-Beta-Preview-NoInstaller.zip
; --------------------------------------------

set a, "\n"
```

The Build Output is this one:
`[22:38] Building solution...`
And never build. IDE is still usable, nothing is wrong, but the project doesn't build. No error message, nothing. Just infinite building time.

**Comment by kierenj** [comment]
Thanks, now fixed.  It will correctly give the error message, "Cannot use a string as an operand".  (You may have intended to use a character literal - '\n' - but special characters like \n, \t, \r are not processed currently etiher)
