### ISSUE TITLE
Internal Assembler error with the HWQ Instruction

### ISSUE THREAD

**Issue by Kelmoir** [kierenj/0x10c-DevKit#79]
Hi, I'm getting an Internal assembly error with those Instructions (the HWQ itself generates it). It occured because of the "," directly following the HWQ term.

Exception:
Error BUI0032: Error building file HardwareScan.10c: Der Index lag außerhalb des Bereichs. Er muss nicht negativ und kleiner als die Auflistung sein.
Parametername: index ()
(The Index was outside of the valid range. It must be not negative and smaller than the Listing)

code:
HWQ,    Z           ; querying the Hardware Data and store it into the Table

**Comment by Bobbias** [comment]
That's because you should not have the "," after the instruction. HWQ along with HWI only take one operand.

Take a look at my pastebin for an example: http://pastebin.com/raw.php?i=RzTvAzCM

**Comment by Kelmoir** [comment]
Yes, I know - see the desc - But an Comiler error, that is complatining about that would be a lot better than recieving an exception from the DevKit.

**Comment by kierenj** [comment]
Yes I agree: bad error messages and usability bugs are just as important to fix:)

**Comment by kierenj** [comment]
This now gives a much nicer error message, fixed for the next release (later today)
