### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MostAwesomeDude** [kierenj/0x10c-DevKit#83]
No license is given for any file in this repository.

**Comment by kierenj** [comment]
Hi!  That's right, at the moment it's only subject to default copyright :)  Do you have a specific question about using the code - how can I help?

**Comment by MostAwesomeDude** [comment]
Well, a license would be nice, so that I can actually check out, read through, and modify the code without worrying about legal issues down the road. (I'm in the USA, so the "default copyright" of publishing, plus Github's ToS, pretty much limit the people that can view, edit, and redistribute your code to you and the Githubbers.)

**Comment by kierenj** [comment]
Ok, looks like I would want to go with the GPL for now.  I will add a license file with the next commit.
