### ISSUE TITLE
A new kernel endeavor

### ISSUE THREAD

**Issue by avaidyam** [kierenj/0x10c-DevKit#84]
https://github.com/galaxas0/MachX-Kernel

Hopefully someone's willing to join me in this. I can assure you I know what I'm doing, and if anyone was wondering "Well, who the hell uses a kernel like that?", iPhones, iPads, Mac OS X.

**Comment by kierenj** [comment]
This is an Issue tracker for 0x10c DevKit.  Unless MachX-Kernel is a bug can I close this..?

**Comment by avaidyam** [comment]
This is true, my bad, the main site pointed me here, but okay. Where would I ask this sort of question?

**Comment by kierenj** [comment]
It depends, who do you want to pose the question to?  The only site I can think which pointed you here would be the 0x10c DevKit site.  I'll close this issue for now, but remain quite confused..
