### ISSUE TITLE
Program Documentation

### ISSUE THREAD

**Issue by GendoIkari** [kierenj/0x10c-DevKit#85]
It would be great if inside program, under Help menu, there were some documentation. The site is not updated anymore, and a detailed help about macros, about specific IDE feature would help.

**Comment by kierenj** [comment]
If you'll bear with me, the site hasn't been updated in a very short while, like a week or two.  "Not updated anymore" I would believe if it had been a couple of months.   I think a help menu is a good idea, but it would link to the online manual.]
In the meantime, are there any specific queries you have, and I'll do my best to explain/help? :)
