### ISSUE TITLE
Multiple instances of plugins/hardware

### ISSUE THREAD

**Issue by Bobbias** [kierenj/0x10c-DevKit#86]
It would be nice to be able to say, hook up 2 monitors to the emulated computer.

Or 2 floppy drives, etc. I could see using multiple instances of hardware being very useful, and unless your code for plugins is really convoluted, it shouldn't be too difficult to implement either.

**Comment by kierenj** [comment]
Very nice idea and certainly possible.  Thankfully the code is very modular, will require a minor modification to the UI code interface to allow multiple controls.  Would love to include this in a future release.

**Comment by kierenj** [comment]
Implemented for LEM1802 and easily extended to other plugin hardware.  Looks cool for 2,5 or 10 screens! :)

**Comment by Bobbias** [comment]
Awesome, thanks! That should make it easier to simulate a more game-like environment, as well as let people create higher resolution output by spanning multiple screens :P
