### ISSUE TITLE
Case insensitive names

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#88]
As recommended by the [0x10c standards committee](https://github.com/0x10cStandardsCommittee/0x10c-Standards/blob/master/ASM/Spec_0xSCA.txt) (section 3, not really a standard by the way), and also implemented by a number of other popular assemblers (for instance [0x10co.de](http://0x10co.de) and [dcpu.ru](http://dcpu.ru)), I would like to see that labels, macros and definitions would become case insensitive.

**Comment by kierenj** [comment]
Sounds like a good idea. Will implement:)

**Comment by kierenj** [comment]
Names are now case insensitive, added unit test to ensure this.  Will be included in the next release.  Thanks for the feedback!
