### ISSUE TITLE
Add memory viewer

### ISSUE THREAD

**Issue by Cupcakus2** [kierenj/0x10c-DevKit#90]
It would be awesome-o if there was a way to view memory in the emulator while debugging without having to create a watch for each address you want to observe.

**Comment by Cupcakus2** [comment]
I didn't notice it already had this, my bad sorry.

**Comment by kierenj** [comment]
There is already a memory view: are you sure you are using the latest version?

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Add memory viewer (#90) 
From: Cupcakus2 reply@reply.github.com 
To: kierenj kierenj@gmail.com 
CC:  

It would be awesome-o if there was a way to view memory in the emulator while debugging without having to create a watch for each address you want to observe.

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/90
