### ISSUE TITLE
Support for constants or defines

### ISSUE THREAD

**Issue by Cupcakus2** [kierenj/0x10c-DevKit#91]
The ability to define constants such as 

```
MyKickassVariable = 0x2012
```

or #define is also just fine

```
#define COLOR_BLACK 0
```

**Comment by kierenj** [comment]
The latest release does include support for # define statements.  Are you running 1.7.2?

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Support for constants or defines (#91) 
From: Cupcakus2 reply@reply.github.com 
To: kierenj kierenj@gmail.com 
CC:  

The ability to define constants such as 

    MyKickassVariable = 0x2012

or #define is also just fine

    #define COLOR_BLACK 0

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/91

**Comment by Cupcakus2** [comment]
OK, so you say this, I try it again and presto it works.  I swear this did not work earlier when I tried it... ugh... my bad again sorry.  I'll close the issue.
