### ISSUE TITLE
Editor Font Change

### ISSUE THREAD

**Issue by lygaret** [kierenj/0x10c-DevKit#92]
It would be awesome to be able to use a monospaced font in the editor. Right now I'm copy pasting from my normal editor in.

**Comment by kierenj** [comment]
The editor font should be monospaced already: Consolas.   Can I ask which OS you  are using?  Perhaps the next installer can include the font.

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Editor Font Change (#92) 
From: Jon Raphaelson reply@reply.github.com 
To: kierenj kierenj@gmail.com 
CC:  

It would be awesome to be able to use a monospaced font in the editor. Right now I'm copy pasting from my normal editor in.

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/92

**Comment by kirinyaga** [comment]
it's not a monospace for me neither. Don't know which one exactly, a sansserif font, maybe an arial narrow or something. That's probably why I found the font very small : it's not the one you see :p
I use WinXP and I don't see the Consolas font in my os font repository. There is the ubiquitous Courier however.

**Comment by kierenj** [comment]
I will either include Consolas in the installer (license permitting) or have it fall back to another font

**Comment by kierenj** [comment]
In the meantime you can download it from here, by the way: http://www.microsoft.com/en-us/download/details.aspx?id=17879

**Comment by kirinyaga** [comment]
aaaah, much better !

**Comment by kierenj** [comment]
Changed all font selection to fall back to Courier New if no Consolas was found
