### ISSUE TITLE
Font Colours problem

### ISSUE THREAD

**Issue by astromechza** [kierenj/0x10c-DevKit#93]
Font foreground and background colours still not right.
I know you said you fixed this but it is still giving problems. Easier to see now that the memory editor is available.
With my display mapped to 0xE000 I am still getting the wrong colours displayed:

![Screenshot](http://i1242.photobucket.com/albums/gg534/AstromechZA/ss2.jpg)

**Comment by kierenj** [comment]
Hi - I just checked writing F2-based colours to E000 with the display mapped there.  It displays correctly as white-on-green.  Tested on latest debug build first, and also the installed 1.7.2 release.  Also created a colour chart,which displays OK.  Is there any chance you're not using the default palette?  If you believe you are, perhaps you can post your code?

**Comment by astromechza** [comment]
In my screen setup event:

```
    ; X is the hardware address, 0, 1 or 2 at the moment.
    . . .

   ;map memory
    SET A, 0
SET B, [lem1802_base_address]
HWI X
    ;map font, (default)
SET A, 1
SET B, 0
HWI X
    ;map palette (default)
SET A, 2
SET B, 0
HWI X
    ;set border color, at this stage C = 0x1
SET A, 3
SET B, C
HWI X
SET PC, POP   ;break out
```

Don't see anything wrong with that. Should I attempt full reinstall? Are there any configs that could be related?

**Comment by kierenj** [comment]
Ah Ive never tested the fubctionailty of settibg the palette address to 0.  It could be reading from offset 0 incorrectly!  Try it wjthout that call and I will review the code when I can.  Excuse the typos - on a phone ;)

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: Re: [0x10c-DevKit] Font Colours problem (#93) 
From: AstromechZA reply@reply.github.com 
To: kierenj kierenj@gmail.com 
CC:  

In my screen setup event:

        ; X is the hardware address, 0, 1 or 2 at the moment.
        . . .

       ;map memory
        SET A, 0
SET B, [lem1802_base_address]
HWI X
        ;map font, (default)
SET A, 1
SET B, 0
HWI X
        ;map palette (default)
SET A, 2
SET B, 0
HWI X
        ;set border color, at this stage C = 0x1
SET A, 3
SET B, C
HWI X
SET PC, POP   ;break out

Don't see anything wrong with that. Should I attempt full reinstall? Are there any configs that could be related?

---

**Comment by astromechza** [comment]
Ah ok, I was following the LEM1802 spec that says " If B is 0, the
default palette is used instead.", so I don't have a palette at
address 0.

No problem, thanks for the quick reply.

On Thu, May 3, 2012 at 6:51 PM, kierenj
reply@reply.github.com
wrote:

**Comment by kierenj** [comment]
Great thanks for looking into that, will fix as a priority.

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: Re: [0x10c-DevKit] Font Colours problem (#93) 
From: AstromechZA reply@reply.github.com 
To: kierenj kierenj@gmail.com 
CC:  

Ah ok, I was following the LEM1802 spec that says " If B is 0, the
default palette is used instead.", so I don't have a palette at
address 0.

No problem, thanks for the quick reply.

On Thu, May 3, 2012 at 6:51 PM, kierenj
reply@reply.github.com
wrote:

> Ah Ive never tested the fubctionailty of settibg the palette address to 0.  It could be reading from offset 0 incorrectly!  Try it wjthout that call and I will review the code when I can.  Excuse the typos - on a phone ;)
> 
> Sent from Samsung Galaxy Note
> 
> -------- Original message --------
> Subject: Re: [0x10c-DevKit] Font Colours problem (#93)
> From: AstromechZA reply@reply.github.com
> To: kierenj kierenj@gmail.com
> CC:
> 
> In my screen setup event:
> 
>         ; X is the hardware address, 0, 1 or 2 at the moment.
>         . . .
> 
>        ;map memory
>         SET A, 0
> SET B, [lem1802_base_address]
> HWI X
>         ;map font, (default)
> SET A, 1
> SET B, 0
> HWI X
>         ;map palette (default)
> SET A, 2
> SET B, 0
> HWI X
>         ;set border color, at this stage C = 0x1
> SET A, 3
> SET B, C
> HWI X
> SET PC, POP   ;break out
> 
> Don't see anything wrong with that. Should I attempt full reinstall? Are there any configs that could be related?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kierenj/0x10c-DevKit/issues/93#issuecomment-5491749
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kierenj/0x10c-DevKit/issues/93#issuecomment-5492235

---

**Comment by astromechza** [comment]
Also double checked palette ram by dumping it. here's a labelled screenshot:
![Screenshot](http://i1242.photobucket.com/albums/gg534/AstromechZA/ss3.jpg)

**Comment by kierenj** [comment]
I checked the same code and couldn't reproduce.  Is there any way you could send me your whole solution (including .10csln file)?  You can email it to 0x10cdevkit@gmail.com - obviously will be treated with confidentiality.

**Comment by astromechza** [comment]
Omw, now I feel like an idiot. Did a complete wipe and reinstall of dev-kit. Deleted the .bin and checked things. It now works perfectly.. Thanks a lot
please close.
