### ISSUE TITLE
add source segments / sections

### ISSUE THREAD

**Issue by DustyMonkey** [kierenj/0x10c-DevKit#94]
Currently all instructions/dats assemble in order into the same output stream.

Many assemblers (and compilers) divide programs up into segments/sections named 'text' (most code goes here), 'data' (most data declarations go here), and so forth so that not every statement needs to be sequentially stated.

a simple use would be to avoid silly branches over data generated in macros:
# macro print(s) {

  segment data
  .foo: dat s

  segment text
  set x, foo
  jsr puts
}

print "hello world!"

An advanced use would be for a set of source files to leverage a common segment for initialization pointers, so that a source file can alert the bootstrap code that it needs that initialization...

For example, mem_manager.10c might have the basic form:

segment initializers

  dat init_memory_manager

segment text

:init_memory_manager
  ; set up initial values

:alloc
  ; stuff

:free
  ; stuff

a generic bootstrap could loop over all the values in the initializers segment, allowing the programmer to simply load or unload library files that leverage the initializer segment without having to fart around with inserting or deleting calls to initializers within the bootstrap... that might look something like:

; make sure segments are created:

segment initializers           ; make sure this segment exists
segment initializersa         ; and when segments are sorted alphabetically, this one marks the end of the initializers segment
segment aaaabootstrap   ; should always sort up to the first segment

:bootstrap

  set x, initializers
  set y, initializersa
  .loop:
    ife x, y
    set pc, main
    jsr [x]
    set pc, loop

As an added bonus, when segments are sorted alphabetically you no longer have to solve the issue of the bootstrap having to be in the first source file of the first project... the end user can simply make sure that his bootstrap segment has a priority name.

**Comment by DustyMonkey** [comment]
:( missed an add x, 1 in that last bit of code .. I have no excuse.

**Comment by kierenj** [comment]
Good idea, thanks for the feedback.  This is likely to become more and more useful as things get more complex

**Comment by kierenj** [comment]
This is being implemented now, it comes in very handy when implementing relocatable code.:)

**Comment by kierenj** [comment]
Now implemented, and it's quite awesome.

#segment name [priority]

Default order: boot,code,text,default,data,bss,heap,stack.  Default segment is "default".

Other segments can be named whatever you like and given a custom priority.  Priority for the above segments can be overridden too.
