### ISSUE TITLE
Crash on Start-up (1.7.2) Can't run IDE at all.

### ISSUE THREAD

**Issue by Logic-Bomb** [kierenj/0x10c-DevKit#95]
Sent an error report, but basically, It won't run at all.
Running on;

Windows 7 Home - 3.5gb RAM, Intel Q6600 Quad Core CPU & Nvidia 8600 GPU.

Can't understand why it won't run.

**Comment by kierenj** [comment]
Ack, I will look into this now..

**Comment by kierenj** [comment]
Did you enter your email address when submitting?  If so could you let me know what it is please?

**Comment by Logic-Bomb** [comment]
Yes I did, It was Kizbits2000@gmail.com
=)

**Comment by kierenj** [comment]
I am reading the report now.  It's quite odd!  Would you mind trying something for me - uninstalling and then reinstalling please, I have a hunch?  (Making sure the Devkit program files folder is empty before reinstalling?)

**Comment by Logic-Bomb** [comment]
Wow... That's really odd... o.o Seems to have fixed it, where-as repair hadn't, sorry I didn't think to do that before hand. Thanks for you help, I'd say this is resolved now, although i'll create a new issue if it starts happening again! =)

Thanks! 

Kiz.

**Comment by kierenj** [comment]
I think I know what it could be (left over file from old version).. will fix that one for the next release.  Thanks for the help!
