### ISSUE TITLE
Bug: Defines causing "Cannot modify operand"

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#96]
```
#define foo [__foo]
SET foo, 0x1
SUB PC, 1 ; halt forever
:__foo DAT 0
```

I would expect that the definition of foo would expand first, so that the above code would become the same as:

```
SET [__foo], 0x1
SUB PC, 1
:__foo DAT 0
```

But instead of assembling it gives me the error message "Cannot modify operand".

**Comment by kierenj** [comment]
Fixed for the next release, thanks for the feedback :)
