### ISSUE TITLE
Expressions in reserve directives

### ISSUE THREAD

**Issue by frxstrem** [kierenj/0x10c-DevKit#97]
It would be useful to be able to use expressions and #define'd constants in `RESERVE` directives, such as:

```
:foo
    RESERVE 0x10
    ; currently works as expected (16 words reserved)
:foo_end

:bar
    RESERVE (foo_end - foo)
    ; currently ExpectedLiteralException
:bar_end

#define baz_length 12
:baz
    RESERVE baz_length
    ; currently no errors, but no words are reserved
:baz_end
```

**Comment by kierenj** [comment]
This is now partially fixed/implemented: the first and last cases will work.  The middle one however requires a change to the architecture and I believe is a corner-case with little use.  It might be tackled/added in the future but for now, RESERVE expressions must be able to be resolved without referring to labels
